import type { NextPage } from 'next';
import Head from 'next/head';

import SignUpScreen from '@features/auth/signup/SignUp.screen';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SignUpScreen />
    </div>
  );
};

export default Home;
